spring:
  application:
      name: admin-server-dev
  datasource:
    url: jdbc:mysql://yyn_db.youyinian.cn/yyn_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: youyinian
    password: 29b03671fd2
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 200
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
#    tomcat:
#      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)



  redis:
     database: 0
     host: 127.0.0.1
     port: 6379
     password:
     pool:
       max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
       max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
       max-idle: 8    # 连接池中的最大空闲连接
       min-idle: 1    # 连接池中的最小空闲连接
     timeout: 5000    # 连接超时时间（毫秒）
  redis2:
     host: 127.0.0.1
     port: 6379

  http:
    encoding:
      charset: utf-8
    converters:
          preferred-json-mapper: fastjson

server:
  undertow:
      io-threads: 4
      worker-threads: 50
      buffer-size: 1024
      direct-buffers: true
      accesslog:
        enabled: true
        dir: /diska/admin-logs
        prefix: admin_youyinian_access_log
      max-http-post-size: 10485760
  port: 8091
  address: 127.0.0.1
  tomcat:
    accesslog:
      directory: /User/jl/data/logs
#      suffix: .log
      prefix: admin_access_log
      enabled: true

    max-threads: 2000
    min-spare-threads: 30
    max-connections: 5000
    max-http-post-size: 10485760

logging:
  config: classpath:log-dev.xml



#url: jdbc:mysql://yyn_db.youyinian.cn/yyn_db?useUnicode=true&characterEncoding=utf8
#username: youyinian
#password: 29b03671fd2

security:
  user:
    name: haku-admin
    password: haku5201314
  basic:
    enabled: true
    path: /remote/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://haku-admin:haku5201314@localhost:6001/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 10
      metadataMap:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
        
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
MaxAutoRetriesNextServer: 1
