spring:
  application:
    name: admin-server
  datasource:
    url: jdbc:mysql://yyn_db.youyinian.cn/yyn_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: youyinian
    password: 29b03671fd2
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 200
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    tomcat:
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=100)
#  data:
#    elasticsearch:
#      cluster-name: yyn_elastic
#      cluster-nodes: 127.0.0.1:9300
#      repositories:
#        enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 500  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 200    # 连接池中的最大空闲连接
      min-idle: 50   # 连接池中的最小空闲连接
    timeout: 5000    # 连接超时时间（毫秒）
  redis2:
    host: 10.104.10.188
    port: 63791

  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  http:
    encoding:
      charset: utf-8
    converters:
          preferred-json-mapper: fastjson

server:
  undertow:
    io-threads: 4
    worker-threads: 50
    buffer-size: 1024
    direct-buffers: true
    accesslog:
      enabled: true
      dir: /data/admin-logs
      prefix: admin_youyinian_access_log
    max-http-post-size: 10485760
  port: 8091
  address: 10.104.179.20
  tomcat:
    accesslog:
      directory: /diska/admin-logs
#      suffix: .log
      prefix: admin-youyinian_access_log
      enabled: true

    max-threads: 2000
    min-spare-threads: 30
    max-connections: 5000
    max-http-post-size: 10485760

logging:
  config: classpath:log-prod.xml

security:
  user:
    name: haku-admin
    password: haku5201314
  basic:
    enabled: true
    path: /remote/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://haku-admin:haku5201314@eureka-master:6001/eureka/,http://haku-admin:haku5201314@eureka-slave1:6002/eureka/,http://haku-admin:haku5201314@eureka-slave2:6003/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
