spring:
    profiles:
        active:
        - dev

---
server:
    prot: 8201
spring:
    profiles: dev
    application:
        name: client-dev

---
server:
    prot: 8202
spring:
    profiles: test
    application:
        name: client-test